### ISSUE TITLE
warning in fap.pm - perl depricating reg-ex syntax

### ISSUE THREAD

**Issue by bradanlane** [hessu/perl-aprs-fap#1]
I've recently moved an application to a new server and - in the process - updated perl to 5.22.

It now throws a warning on FAP.pm:

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^{{ <-- HERE / at FAP.pm line 2712.
```

I'm not clear on what the section of cod is search for so I am not sure what is the correct change to the reg-ex.

_Note: Perl 5.26 will treat this as an error and quit._

**Comment by hessu** [comment]
Hi, thanks for the report. This is fixed in commit 84d796de105df7b5bb0d4123692f509ef2ef2949.
