### ISSUE TITLE
Sending negative decimal GPS coordinates

### ISSUE THREAD

**Issue by ajkirby** [hessu/perl-aprs-fap#2]
I'm having issues sending GPS data captured from DMR digital radios to FAP.pm

If the latitude value is a minus number I get undef back from FAP.

 51.8810034 -359.437142 causes undef

51.941111 0.633388 works

Here's the code I'm using:

    foreach my $ent (@upd_q) {
        my $aprs_position = Ham::APRS::FAP::make_position(
            $ent->{'latitude'},
            $ent->{'longitude'},
            -1, # speed
            -1, # course
            -10000, # altitude
            (defined $ent->{'symbol'}) ? $ent->{'symbol'} : '/[', # symbol
            1, # compression
            0); # no ambiguity
        #print "$aprs_position\n";

        my $packet = sprintf('%s>APTR01:!%s', $ent->{'callsign'}, $aprs_position);
        #print "$packet\n";

	if ($aprs_enable == 1){
            my $ok = $is->sendline($packet);
            if (!$ok) {
                $is->disconnect();
            }
	}
    }

I realise this is likely a problem with the above code and not FAP but I'm struggling to debug this so any help would be great.

**Comment by johnlaur** [comment]
You answered your own question. -359.437142 is an invalid longitude in WGS84 datum. It should be in the range -180..180. If you are getting this value from some hardware you will have to test and convert it to be within the correct range by adding or subtracting 360 degrees.

**Comment by ajkirby** [comment]
Ah I see, that makes sense. This is the value coming from the radio using the code at:

https://github.com/KD8EYF/TRBO-NET

I'll try adding a line to add 360 degrees to the longitude.

Thanks.

**Comment by hessu** [comment]
@ajkirby is right, longitude range is -180 to 180 degrees (a range of 360 degrees, with 0 degrees at Greenwich), -359 would be an extra round around the world. Happy hacking!

**Comment by ajkirby** [comment]
It worked, thanks :-) somebody had subtracted 360 from the longitude coordinate in the code. 
With that now removed the correct packet is assembled and the positions are being shown on APRS.FI (thanks for the great website by the way)
